-- Altera as colunas para NOT NULL
ALTER TABLE pessoas MODIFY (nome VARCHAR2(100) NOT NULL);
ALTER TABLE pessoas MODIFY (apelido VARCHAR2(100) NOT NULL);
ALTER TABLE pessoas MODIFY (data_nascimento DATE NOT NULL);
ALTER TABLE pessoas MODIFY (peso NUMBER(10,2) NOT NULL);
ALTER TABLE pessoas MODIFY (altura NUMBER(10,2) NOT NULL);
ALTER TABLE pessoas MODIFY (sexo VARCHAR2(1) NOT NULL);
ALTER TABLE pessoas MODIFY (pais_origem VARCHAR2(100) NOT NULL);
ALTER TABLE pessoas MODIFY (nacionalidade VARCHAR2(100) NOT NULL);
ALTER TABLE pessoas MODIFY (idiomas VARCHAR2(200) NOT NULL);
ALTER TABLE pessoas MODIFY (marcas_distintivas VARCHAR2(200) NOT NULL);
ALTER TABLE pessoas MODIFY (cor_olhos VARCHAR2(50) NOT NULL);
ALTER TABLE pessoas MODIFY (cor_cabelo VARCHAR2(50) NOT NULL);
ALTER TABLE pessoas MODIFY (mandados_prisao VARCHAR2(200) NOT NULL);
ALTER TABLE pessoas MODIFY (tipo_crime VARCHAR2(255) NOT NULL);
ALTER TABLE pessoas MODIFY (descricao VARCHAR2(255) NOT NULL);
ALTER TABLE pessoas MODIFY (data_crime DATE NOT NULL);
